### ISSUE TITLE
Not able to run Load on Demand Example

### ISSUE THREAD

**Issue by kartset** [nowaalex/af-utils#28]
I was trying to use [Load On Demand](https://af-utils.vercel.app/virtual/examples/list/LoadOnDemand) example but if I copy paste the entire example code provided on the link, I get an infinite scrollable list with costant additions of new posts without even scrolling which is not really the behavior shown on the website which works perfectly. I even tried to clone this repository so that I can check the code you might have used for website but no luck. Click [here](https://stackblitz.com/edit/react-xhrqyu?file=src/App.js) to see the output if we copy the code from the website. There was only one change that I did, I copied the useFakerseed code from the repository in the example.

**Comment by nowaalex** [comment]
1.) This website is built with tailwindcss. h-full class means height: 100%. Without tailwind it is useless.
2.) List's desire to stretch vertically should be limited somehow. Some options:
   * provide explicit height to the list
   * provide explicit height to list parent and use `height: 100%` on the list. Or use flex/grid instead of providing full height.
   * use `position: relative` on list parent and `position: absolute; inset: 0;` on the list.

**Comment by kartset** [comment]
Hi @nowaalex, I implemented your suggestions in the same sandbox and it is working as expected now. Thanks.
